spring:
  datasource:
    url: jdbc:mysql://servidor-produccion-ip:3306/lista_espera_prod
    username: root
    password: Gab714@
  
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false 

logging:
  level:
    root: INFO
    com.rednorte.listaespera: INFO