# CONFIGURACIÓN PARA DOCKER
spring.datasource.url=jdbc:mysql://localhost:3307/rednorte_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=user_rednorte
spring.datasource.password=admin123


# Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect