server:
  port: 8001

spring:
  application:
    name: ms-usuarios
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  jackson:
    date-format: dd/MM/yyyy
    time-zone: America/Santiago

logging:
  level:
    root: INFO
    com.rednorte.msusuarios: INFO