server {
    listen 80;
    
    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        # Redirige cualquier ruta no encontrada al index.html de React
        try_files $uri $uri/ /index.html;
    }

    # Ignorar errores por falta de favicon
    location = /favicon.ico {
        log_not_found off;
        access_log off;
    }
}